# ╔════════════════════════════════════════════════════╗
# ║            Startship Configuration 🚀✨            ║
# ╚════════════════════════════════════════════════════╝



# ----------- Prompt -----------

# Inserts a blank line between shell prompts
add_newline = false

# Use custom format
format = "$all$directory$character"

# Custom format icons
[directory]
read_only = " 󰌾"

# ----------- END -----------



# ╔════════════════════════════════════════════════════╗
# ║                         END                        ║
# ╚════════════════════════════════════════════════════╝
