# ╔════════════════════════════════════════════════════╗
# ║            Startship Configuration 🚀✨            ║
# ╚════════════════════════════════════════════════════╝



# Use custom format
format = '$all$directory$character'



# ╔════════════════════════════════════════════════════╗
# ║                         END                        ║
# ╚════════════════════════════════════════════════════╝
