# ╔════════════════════════════════════════════════════╗
# ║            Startship Configuration 🚀✨            ║
# ╚════════════════════════════════════════════════════╝



# ----------- Prompt -----------

# Inserts a blank line between shell prompts
add_newline = false

# Use custom format
format = '$all$directory$character'

# ----------- END -----------



# ╔════════════════════════════════════════════════════╗
# ║                         END                        ║
# ╚════════════════════════════════════════════════════╝
